---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger-deployment
  labels:
    app: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      # nodeSelector:
      #   system: secondOne
      containers:
      - name: debugger
        image: "{AcctId}.dkr.ecr.us-west-2.amazonaws.com/test:debugger"
        ports:
        - containerPort: 80
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
