apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 512Mi
      defaultRequest:
        memory: 128Mi
      max:
        cpu: "400m"
      min:
        cpu: "20m"
      type: Container
