---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  # hostNetwork: true
  # dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      limits:
        cpu: 200m
        memory: 20Mi
  # initContainers:
  # - name: init-myservice
  #   image: busybox
  #   command:
  #     - /bin/sh
  #     - -c
  #     - sysctl -w net.netfilter.nf_conntrack_max=524277
  #   securityContext:
  #     privileged: true
  # # Note: this won't actually work just more a test to show the separate namespaces at play
  # - name: ulimitchange
  #   image: busybox
  #   command: ['sh', '-c', 'ulimit -a && ulimit -c 2 && ulimit -a']
  # - name: ulimitchange2
  #   image: busybox
  #   command: ['sh', '-c', 'sysctl net.netfilter.nf_conntrack_max']
