apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: kube-public
  labels:
    name: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    run: webserver-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: webserver
