apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        appdb: rsvpdb
    spec:
      containers:
        - name: rsvp-db
          image: mongo:3.3
          env:
            - name: MONGODB_DATABASE
              value: rsvpdata
          ports:
            - containerPort: 27017
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
        - name: rsvp-app
          image: teamcloudyuga/rsvpapp
          env:
            - name: MONGODB_HOST
              value: mongodb
            - name: TEXT1
              valueFrom:
                configMapKeyRef:
                  name: customer1
                  key: TEXT1
            - name: TEXT2
              valueFrom:
                configMapKeyRef:
                  name: customer1
                  key: TEXT2
            - name: COMPANY
              valueFrom:
                configMapKeyRef:
                  name: customer1
                  key: COMPANY
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-password
                  key: pw.txt
          ports:
            - containerPort: 5000
              name: web-port
          volumeMounts:
            - name: password
              mountPath: "/etc/password"
              readOnly: true
      volumes:
        - name: password
          secret:
            secretName: my-password
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
    - host: blue.web.com
      http:
        paths:
          - backend:
              serviceName: rsvp
              servicePort: 80
    - host: green.web.com
      http:
        paths:
          - backend:
              serviceName: green-service
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rsvp
  labels:
    apps: rsvp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web-port
      protocol: TCP
  selector:
    app: rsvp
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: rsvpdb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    appdb: rsvpdb
