apiVersion: v1
entries:
  x-ray:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-07-10T19:26:57.250081764+10:00"
    description: A Helm chart for Kubernetes to create a DaemonSet for the AWS X-Ray
      daemon
    digest: 535db5db2a0faaf25e2dc6f519f931e9fb65aa78e6d06bc2f57180a8cbd157e4
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Peace_sign.svg/500px-Peace_sign.svg.png
    maintainers:
    - name: marjamis
    name: x-ray
    urls:
    - https://marjamis.github.io/k8s_manifests/charts/x-ray-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-10T19:26:57.249730534+10:00"
