apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {CA}
    server: https://{IP}:6443
  name: kc
contexts:
- context:
    cluster: kc
    namespace: default
    user: kc
  name: kc
current-context: kc
kind: Config
preferences: {}
users:
- name: kc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: docker
      args:
      - run
      - -it
      - --rm
      - 894847497797.dkr.ecr.us-west-2.amazonaws.com/aws-iam-authenticator:0.4.0-alpha.1-alpine-3.7
      - token
      - -i
      - kc
