---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: metrics-server
  chart:
    repository: stable/metrics-server
    name: metrics-server
