apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-18
  region: us-west-2
  version: '1.18'
  tags:
    'env': 'testing'
    'auto-delete': 'no'

# availabilityZones:
#   - us-west-2a
#   - us-west-2b
#   - us-west-2c
vpc:
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  subnets:
    public:
      AZ-a: {id: subnet-{id}}
      AZ-b: {id: subnet-{id}}
      AZ-c: {id: subnet-{id}}
    private:
      AZ-a: {id: subnet-{id}}
      AZ-b: {id: subnet-{id}}
      AZ-c: {id: subnet-{id}}

fargateProfiles:
  - name: default
    selectors:
      - namespace: fargate
  - name: dev
    selectors:
      - namespace: dev
        labels:
          env: dev

nodeGroups:
  - name: new-default
    labels: {role: workers}
    instanceType: m5.xlarge
    desiredCapacity: 1
    kubeletExtraConfig:
      kubeReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      evictionHard:
          memory.available:  "200Mi"
          nodefs.available: "10%"
    ssh:
      allow: true
      publicKeyPath: testing
    privateNetworking: false
    ami: ami-04f0f3d381d07e0b6
    tags:
      "auto-delete": "no"
  - name: new-secondaryNodeGroup
    labels: {role: workers}
    instanceType: m5.xlarge
    desiredCapacity: 1
    kubeletExtraConfig:
      kubeReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      evictionHard:
          memory.available:  "200Mi"
          nodefs.available: "10%"
    ssh:
      allow: true
      publicKeyPath: testing
    ami: ami-04f0f3d381d07e0b6
    tags:
      "auto-delete": "no"
  - name: bottlerocket
    instanceType: m5.xlarge
    desiredCapacity: 1
    amiFamily: Bottlerocket
    ami: auto-ssm
    labels: {role: workers, os_type: bottlerocket}
    # More details on the new settings can be found here: https://eksctl.io/usage/schema/
    bottlerocket:
      enableAdminContainer: true
      # More details on settings can be found here: https://github.com/bottlerocket-os/bottlerocket/#description-of-settings. Note: eksctl will want some of these in other locations of the nodegroup settings.
      settings:
        motd: "Hello, eksctl!"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

git:
  repo:
    url: "git@github.com:marjamis/k8s_manifests.git"
    branch: master
    fluxPath: "cluster_baseline/flux/"
    email: "exclusive.cipher@gmail.com"
  operator:
    namespace: "flux"
    withHelm: true
