apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2
  version: '1.16'
  tags:
    env: testing

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
vpc:
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
#   subnets:
#     public:
#       AZ-a: {id: subnet-XXX}
#       AZ-b: {id: subnet-XXX}
#       AZ-c: {id: subnet-XXX}
#     private:
#       AZ-a: {id: subnet-XXX}
#       AZ-b: {id: subnet-XXX}
#       AZ-c: {id: subnet-XXX}

fargateProfiles:
  - name: default
    selectors:
      - namespace: fargate
  - name: dev
    selectors:
      - namespace: dev
        labels:
          env: dev

nodeGroups:
  - name: default
    labels: {role: workers}
    instanceType: m5.xlarge
    desiredCapacity: 1
    kubeletExtraConfig:
      kubeReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      evictionHard:
          memory.available:  "200Mi"
          nodefs.available: "10%"
    ssh:
      allow: true
      publicKeyPath: testing
    privateNetworking: false
    ami: ami-0d038c77c015e1353
    tags:
      "auto-stop": "never"
      "auto-delete": "never"
  - name: secondaryNodeGroup
    labels: {role: workers}
    instanceType: m5.xlarge
    desiredCapacity: 1
    kubeletExtraConfig:
      kubeReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      evictionHard:
          memory.available:  "200Mi"
          nodefs.available: "10%"
    ssh:
      allow: true
      publicKeyPath: testing
    ami: ami-0d038c77c015e1353
    tags:
      "auto-stop": "never"
      "auto-delete": "never"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

git:
  repo:
    url: "git@github.com:marjamis/k8s_manifests.git"
    branch: master
    fluxPath: "cluster_baseline/flux/"
    email: "exclusive.cipher@gmail.com"
  operator:
    namespace: "flux"
    withHelm: true
